<a href="https://colab.research.google.com/github/Lattemelia/Portforio/blob/main/demand%20forecasting1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 新しいセクション

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
PATH = r"/content/drive/MyDrive/Colab Notebooks"

test_df = pd.read_csv(PATH + r"/test.csv")
train_df = pd.read_csv(PATH + r"/train.csv")

marged_df = pd.concat([test_df,train_df],axis=0)

In [10]:
marged_df

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,extracted_engine,engine_displacement,engine_type
0,188533,Land,Rover LR2 Base,2015,98000,Gasoline,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,White,Beige,None reported,Yes,NaN,2.0L 4 Cylinder,2.0L,4 Cylinder
1,188534,Land,Rover Defender SE,2020,9142,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Silver,Black,None reported,Yes,NaN,3.0L Straight 6,3.0L,Straight 6
2,188535,Ford,Expedition Limited,2022,28121,Gasoline,3.5L V6 24V PDI DOHC Twin Turbo,10-Speed Automatic,White,Ebony,None reported,NaN,NaN,3.5L V6 24V,3.5L,V6 24V
3,188536,Audi,A6 2.0T Sport,2016,61258,Gasoline,2.0 Liter TFSI,Automatic,Silician Yellow,Black,None reported,NaN,NaN,2.0 Liter TFSI,2.0,Liter TFSI
4,188537,Audi,A6 2.0T Premium Plus,2018,59000,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Black,None reported,Yes,NaN,2.0L 4 Cylinder,2.0L,4 Cylinder
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188528,188528,Cadillac,Escalade ESV Platinum,2017,49000,Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Beige,None reported,Yes,27500.0,6.2L 8 Cylinder,6.2L,8 Cylinder
188529,188529,Mercedes-Benz,AMG C 43 AMG C 43 4MATIC,2018,28600,Gasoline,385.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Black,At least 1 accident or damage reported,Yes,30000.0,3.0L V6 Cylinder,3.0L,V6 Cylinder
188530,188530,Mercedes-Benz,AMG GLC 63 Base 4MATIC,2021,13650,Gasoline,469.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,White,Black,None reported,Yes,86900.0,4.0L 8 Cylinder,4.0L,8 Cylinder
188531,188531,Audi,S5 3.0T Prestige,2022,13895,Gasoline,3.0L,1-Speed Automatic,Daytona Gray Pearl Effect,Black,None reported,NaN,84900.0,NaN,NaN,NaN
188532,188532,Porsche,Macan Base,2016,59500,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Black,None reported,Yes,28995.0,2.0L 4 Cylinder,2.0L,4 Cylinder

In [11]:
marged_df.isnull().sum()

id                          0
brand                       0
model                       0
model_year                  0
milage                      0
fuel_type                8466
engine                      0
transmission                0
ext_col                     0
int_col                     0
accident                 4084
clean_title             35658
price                  125690
extracted_engine         7731
engine_displacement      7731
engine_type              7731
dtype: int64

In [9]:
#エンジン名のみ抽出
regex_pattern = r"(?:^\d+\.\d+HP\s+)?([^\s]+\s+[^\s]+\s+[^\s]+)"
marged_df["extracted_engine"] = marged_df["engine"].str.extract(regex_pattern)

#排気量と構造で分ける
split_regex = r"^([^\s]+)\s+(.+)$"

# 2つの新カラム名（容量、エンジン型式）を指定して一撃で代入
marged_df[["engine_displacement", "engine_type"]] = marged_df["extracted_engine"].str.extract(split_regex)